# Generated by Django 4.1.3 on 2022-11-29 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rpas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpas_type', models.CharField(max_length=30)),
                ('rpas_reg', models.CharField(max_length=30)),
                ('airframe_bf', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('location_dep', models.CharField(max_length=30)),
                ('location_arr', models.CharField(max_length=30)),
                ('flight_type', models.CharField(max_length=30)),
                ('pilot', models.CharField(max_length=30)),
                ('crew', models.CharField(max_length=30)),
                ('dep_time', models.DateTimeField()),
                ('arr_time', models.DateTimeField()),
                ('flight_time', models.TimeField()),
                ('airframe_hrs', models.TimeField()),
                ('fuel_start', models.TimeField()),
                ('fuel_end', models.TimeField()),
                ('batt', models.CharField(max_length=30)),
                ('signature', models.IntegerField()),
                ('rpas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone.rpas')),
            ],
        ),
    ]
