# Generated by Django 4.1.3 on 2022-11-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0002_alter_flights_airframe_hrs_alter_flights_flight_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='airframe_hrs',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='flight_time',
        ),
        migrations.AddField(
            model_name='rpas',
            name='airframe_hrs',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpas',
            name='airframe_bf',
            field=models.DurationField(),
        ),
    ]
