# Generated by Django 4.1.3 on 2022-11-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0003_remove_flights_airframe_hrs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='batt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='fuel_end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='fuel_start',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='signature',
            field=models.CharField(max_length=30),
        ),
    ]
