# Generated by Django 4.1.3 on 2022-11-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0004_alter_flights_batt_alter_flights_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arr_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='dep_time',
            field=models.TimeField(),
        ),
    ]
