# Generated by Django 4.1.3 on 2022-11-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0005_alter_flights_arr_time_alter_flights_dep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='arr_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='dep_time',
            field=models.DurationField(),
        ),
    ]
